# Where things are
source              : .
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true
  archives:
    output: true
    permalink: /archives/:path/

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate            : 10
paginate_path       : /page:num
timezone            : America/New_York

quiet               : false
verbose             : false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "Uncategorized"
      author: "acegayhart"
      image:
        path: /assets/images/Ace.png
        height: 200
        width: 200
  - scope:
      path: ""
    values:
        layout: "default"
      

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  

title: "Ace Gayhart"
description: "The blog of technologist and educator, Ace Gayhart."
tagline: "Technologist & Educator"
url: https://acegayhart.com
image: /assets/images/Ace.png
logo:  /assets/images/Ace.png
social:
  name: Ace Gayhart
  links:
    - https://twitter.com/AceGayhart
    - https://www.linkedin.com/in/AceGayhart/
    - https://github.com/AceGayhart/
twitter:
    username: AceGayhart
    card: summary




# author:
#   name: Ace Gayhart
#   uri: https://acegayhart.com/about/

